usb_cam:
    ros__parameters:
        usb_cam_path: "/dev/video0"
        camera_name: ""
        width: 640
        height: 480
        fps: 20
        autostart: true

virtual_cam:
    ros__parameters:
        image_path : "package://rmoss_cam/resource/test.jpg"
        video_path : "package://rmoss_cam/resource/hero.avi"
        camera_name: ""
        frame_id: 'camera_optical_link'
        autostart: true
        use_image_transport_camera_publisher: true