usb_cam:
    ros__parameters:
        usb_cam_path: "/dev/video0"
        camera_name: ""
        width: 640
        height: 480
        fps: 20
        autostart: true

virtual_cam:
    ros__parameters:
        camera_name: ""
        frame_id: 'camera_optical_link'
        autostart: true
        use_image_transport_camera_publisher: true