usb_cam:
    ros__parameters:
        usb_cam_path: "/dev/video0"
        camera_name: ""
        width: 640
        height: 480
        fps: 20
        autostart: true

virtual_video_cam:
    ros__parameters:
        video_path : "../resource/hero.avi"
        camera_name: ""
        autostart: true