/mv_cam_node:
  ros__parameters:
    camera_info_url: package://hero_bringup/config/camera_info.yaml
    exposure_time: 5000
    gain: 32
    use_sensor_data_qos: true
    rgb_gain:
       b: 120
       g: 110
       r: 135

/hik_cam_node:
  ros__parameters:
    camera_inf_url: package://hik_camera/config/camera_info.yaml
    exposure_time: 6000
    gain: 32.0
    use_sensor_data_qos: true
    rgb_gain:
       b: 120
       g: 110
       r: 135
/virtual_cam_node:
    ros__parameters:
        image_path : "package://rmoss_cam/resource/shot.png"
        video_path : "package://rmoss_cam/resource/hero.avi"
        camera_name: ""
        frame_id: 'camera_optical_link'
        autostart: true
        use_image_transport_camera_publisher: true

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.005
    device_name: /dev/ttySerialCom
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/virtual_serial_driver:
  ros__parameters:
    bullet_speed: 26.5
    enemy_color: 82
    pitch_joint: 0.0
    yaw_joint: 0.0

/armor_detector:
  ros__parameters:
    debug: true

    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: gimbal_odom
    max_armor_distance: 10.0

    yaw_angle_thres: 25.0
    fire_permit_thres: 1.5
    fire_latency: 0.03
    min_speed: 12.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 0.0004
      r_yaw: 0.005

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

    trajectory:
      max_iter : 10 
      stop_error : 0.001
      R_K_iter : 50
      init_bullet_speed : 26.5
      is_hero: true
      static_offset:
        yaw : 0.0
        pitch : 0.0
